### ISSUE TITLE
'args' is missing with no default

### ISSUE THREAD

**Issue by aemon-j** [aemon-j/GOTMr#1]
Running GOTMr on Ubuntu and there's an error:
```
run_gotm(sim_folder, args = character())
Error in run_gotmNIX(sim_folder, verbose, args) : 
  argument "args" is missing, with no default
```

**Comment by tadhg-moore** [comment]
This was a function of missing libgfortran3.so libraries. This has been corrected and now Linux users are required to install the gfortran libraries to run GOTM.
